import { Dish } from './types';

export const DISHES: Dish[] = [
  {
    id: '1',
    name: 'Chechebsa (Kita Firfir) with Honey',
    description: 'A traditional Ethiopian breakfast favorite of shredded, freshly baked flatbread tossed in aromatic berbere spice and niter kibbeh (clarified spiced butter), served warm with fresh yogurt and wild forest honey.',
    price: 320,
    category: 'breakfast',
    origin: 'Ethiopian',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=600',
    rating: 4.9,
    reviewsCount: 148,
    ingredients: ['Kita Flatbread', 'Niter Kibbeh', 'Berbere Spice', 'Yogurt', 'Wild Honey', 'Cardamom'],
    calories: 480,
    prepTime: '15 mins',
    isVegetarian: true,
    isPopular: true
  },
  {
    id: '2',
    name: 'Crispy Sambusa Duo',
    description: 'Crispy, golden pastry triangles filled with your choice of spiced minced beef or herbed green lentils, infused with garlic, ginger, and diced green chilies. Served with a side of house awaze sauce.',
    price: 180,
    category: 'breakfast',
    origin: 'Ethiopian',
    image: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?auto=format&fit=crop&q=80&w=600',
    rating: 4.8,
    reviewsCount: 92,
    ingredients: ['Pastry Shell', 'Minced Beef / Lentils', 'Green Chilies', 'Onion', 'Garlic', 'Ginger', 'Awaze Dip'],
    calories: 320,
    prepTime: '10 mins',
    isVegetarian: false,
    isPopular: false
  },
  {
    id: '3',
    name: 'Sizzling Special Beef Tibs',
    description: 'Premium cubed beef sautéed over intense heat with onions, garlic, fresh rosemary sprigs, and green jalapeños, enriched with spiced clarified butter. Served sizzling hot with Injera.',
    price: 550,
    category: 'kebabs',
    origin: 'Ethiopian',
    image: 'https://images.unsplash.com/photo-1603048588665-791ca8aea617?auto=format&fit=crop&q=80&w=600',
    rating: 4.9,
    reviewsCount: 310,
    ingredients: ['Cubed Beef', 'Niter Kibbeh', 'Onions', 'Garlic', 'Green Jalapeños', 'Rosemary', 'Awaze Sauce'],
    calories: 620,
    prepTime: '15 mins',
    isVegetarian: false,
    isPopular: true
  },
  {
    id: '4',
    name: 'Bubbling Shiro Wat in Clay Pot',
    description: 'A beloved vegan staple: velvety ground chickpea flour cooked with garlic, ginger, berbere spice, and olive oil, served bubbling hot in a traditional clay pot (shambel wat) with fresh Injera.',
    price: 380,
    category: 'mains',
    origin: 'Ethiopian',
    image: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?auto=format&fit=crop&q=80&w=600',
    rating: 4.9,
    reviewsCount: 185,
    ingredients: ['Ground Chickpeas', 'Berbere Spice', 'Garlic', 'Ginger', 'Onion', 'Olive Oil', 'Traditional Injera'],
    calories: 410,
    prepTime: '15 mins',
    isVegetarian: true,
    isPopular: true
  },
  {
    id: '5',
    name: 'Aromatic Doro Wat (Royal Chicken)',
    description: 'The crown jewel of Ethiopian cuisine: slow-cooked chicken drumstick simmered for hours in a rich, deeply spiced onion and berbere sauce, served with a hard-boiled egg and fresh homemade cheese (Ayibe) on Injera.',
    price: 600,
    category: 'mains',
    origin: 'Ethiopian',
    image: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&q=80&w=600',
    rating: 5.0,
    reviewsCount: 420,
    ingredients: ['Chicken Drumstick', 'Hard-Boiled Egg', 'Berbere Spice', 'Red Onions', 'Niter Kibbeh', 'Cardamom', 'Ayibe Cheese'],
    calories: 690,
    prepTime: '30 mins',
    isVegetarian: false,
    isPopular: true
  },
  {
    id: '6',
    name: 'Yetsom Beyaynetu (Ultimate Veggie Combo)',
    description: 'A spectacular, colorful platter of traditional vegan dishes including spicy red lentils (Misir Wat), yellow split peas (Ater Kik), simmered collard greens (Gomen), cabbage and carrots (Atkilt Wat), and azifa salad, arranged beautifully on a large Injera circular roll.',
    price: 480,
    category: 'mains',
    origin: 'Ethiopian',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=600',
    rating: 4.9,
    reviewsCount: 415,
    ingredients: ['Misir Wat', 'Ater Kik', 'Gomen', 'Atkilt Wat', 'Azifa Lentil', 'Beetroot Salad', 'Sourdough Injera'],
    calories: 550,
    prepTime: '20 mins',
    isVegetarian: true,
    isPopular: true
  },
  {
    id: '7',
    name: 'Traditional Tomato Salata',
    description: 'A light and zesty Ethiopian side salad of diced vine-ripened tomatoes, sweet red onions, and deseeded green chilies tossed with extra virgin olive oil, fresh lemon juice, and ground black pepper.',
    price: 250,
    category: 'salads',
    origin: 'Ethiopian',
    image: 'https://images.unsplash.com/photo-1515516969-d4008cc6241a?auto=format&fit=crop&q=80&w=600',
    rating: 4.6,
    reviewsCount: 79,
    ingredients: ['Heirloom Tomatoes', 'Red Onions', 'Green Chilies', 'Fresh Lemon', 'Olive Oil', 'Sea Salt', 'Black Pepper'],
    calories: 140,
    prepTime: '8 mins',
    isVegetarian: true,
    isPopular: false
  },
  {
    id: '8',
    name: 'Sizzling Lamb Shekla Tibs',
    description: 'Tender cubed lamb sautéed with onions, garlic, and sliced jalapeños, cooked and served in a traditional clay pot (shekla) with burning charcoal underneath to maintain heat and a rustic smoky aroma.',
    price: 620,
    category: 'kebabs',
    origin: 'Ethiopian',
    image: 'https://images.unsplash.com/photo-1600891964599-f61ba0e24092?auto=format&fit=crop&q=80&w=600',
    rating: 4.9,
    reviewsCount: 220,
    ingredients: ['Cubed Lamb', 'Rosemary', 'Onion', 'Garlic', 'Niter Kibbeh', 'Jalapeños', 'Smoky Clay Grater'],
    calories: 640,
    prepTime: '18 mins',
    isVegetarian: false,
    isPopular: true
  },
  {
    id: '9',
    name: 'Classic Kitfo with Ayibe & Gomen',
    description: 'Finely minced premium raw beef seasoned with mitmita (spicy chili powder blend) and niter kibbeh, served warm (slightly seared, "leb leb" or traditional raw), accompanied by spiced cottage cheese and collard greens.',
    price: 580,
    category: 'mains',
    origin: 'Ethiopian',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&q=80&w=600',
    rating: 4.9,
    reviewsCount: 312,
    ingredients: ['Minced Beef', 'Mitmita Spices', 'Spiced Butter (Kibbeh)', 'Ayibe Cottage Cheese', 'Collard Greens (Gomen)'],
    calories: 710,
    prepTime: '12 mins',
    isVegetarian: false,
    isPopular: true
  },
  {
    id: '10',
    name: 'Spicy Key Wat (Rich Beef Stew)',
    description: 'Melt-in-your-mouth beef chunks slow-simmered in an incredibly rich, thick, and highly spiced gravy made of puréed red onions, berbere spice, ginger, garlic, and clarified spiced butter.',
    price: 520,
    category: 'mains',
    origin: 'Ethiopian',
    image: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?auto=format&fit=crop&q=80&w=600',
    rating: 4.8,
    reviewsCount: 167,
    ingredients: ['Premium Beef Chunks', 'Berbere Spice Mix', 'Red Onions', 'Garlic', 'Ginger', 'Niter Kibbeh', 'Cardamom'],
    calories: 590,
    prepTime: '22 mins',
    isVegetarian: false,
    isPopular: false
  },
  {
    id: '11',
    name: 'Azifa & Buticha Cold Mezze Platter',
    description: 'A cooling duo of seasoned cold salads: Azifa, made of whole green lentils mashed with red onion, mustard powder, and lime juice; and Buticha, a savory chickpea purée whipped with garlic and olive oil.',
    price: 290,
    category: 'salads',
    origin: 'Ethiopian',
    image: 'https://images.unsplash.com/photo-1505576399279-565b52d4ac71?auto=format&fit=crop&q=80&w=600',
    rating: 4.7,
    reviewsCount: 114,
    ingredients: ['Green Lentils', 'Chickpea Flour', 'Mustard Seed Powder', 'Onions', 'Fresh Lime Juice', 'Olive Oil', 'Mild Spices'],
    calories: 280,
    prepTime: '10 mins',
    isVegetarian: true,
    isPopular: false
  },
  {
    id: '12',
    name: 'Honey-Drenched Ethiopian Baklava',
    description: 'Golden-brown, flaky layers of phyllo pastry packed with roasted spiced walnuts and almonds, baked to a perfect crunch and generously saturated with an aromatic honey and cardamom glaze.',
    price: 260,
    category: 'desserts',
    origin: 'Ethiopian Style',
    image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&q=80&w=600',
    rating: 4.8,
    reviewsCount: 95,
    ingredients: ['Phyllo Pastry', 'Walnuts', 'Almonds', 'Cardamom Honey', 'Cinnamon', 'Ghee'],
    calories: 390,
    prepTime: '10 mins',
    isVegetarian: true,
    isPopular: false
  },
  {
    id: '13',
    name: 'Sweet Sambusa with Spiced Honey',
    description: 'Crispy fried sweet triangular pastries filled with a mixture of spiced, sweet mashed sweet potatoes, brown sugar, cardamom, and cinnamon, served hot with a drizzle of warm organic Ethiopian honey.',
    price: 240,
    category: 'desserts',
    origin: 'Ethiopian Style',
    image: 'https://images.unsplash.com/photo-1511018556340-d16986a1c194?auto=format&fit=crop&q=80&w=600',
    rating: 4.9,
    reviewsCount: 204,
    ingredients: ['Crispy Pastry Shell', 'Mashed Sweet Potatoes', 'Cardamom', 'Cinnamon', 'Organic Honey', 'Powdered Sugar'],
    calories: 340,
    prepTime: '12 mins',
    isVegetarian: true,
    isPopular: true
  },
  {
    id: '14',
    name: 'Special Injera Firfir',
    description: 'Fresh sourdough Injera shredded and cooked in a flavorful berbere sauce with clarified spiced butter, fresh herbs, and topped with hard-boiled eggs.',
    price: 340,
    category: 'breakfast',
    origin: 'Ethiopian',
    image: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?auto=format&fit=crop&q=80&w=600',
    rating: 4.8,
    reviewsCount: 112,
    ingredients: ['Sourdough Injera', 'Berbere Sauce', 'Niter Kibbeh', 'Boiled Eggs', 'Onions', 'Garlic'],
    calories: 450,
    prepTime: '12 mins',
    isVegetarian: false,
    isPopular: false
  },
  {
    id: '15',
    name: 'Scrambled Eggs Dulet Style',
    description: 'Farm fresh eggs scrambled with minced onions, vine-ripened tomatoes, and green jalapeños, cooked with a touch of spiced butter. Served with a warm baguette.',
    price: 290,
    category: 'breakfast',
    origin: 'Ethiopian Style',
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&q=80&w=600',
    rating: 4.7,
    reviewsCount: 88,
    ingredients: ['Farm Eggs', 'Minced Onions', 'Tomatoes', 'Green Jalapeños', 'Spiced Butter', 'Warm Bread'],
    calories: 310,
    prepTime: '10 mins',
    isVegetarian: true,
    isPopular: false
  },
  {
    id: '16',
    name: 'Flame-Grilled Beef Skewers',
    description: 'Tender cubed sirloin beef marinated in berbere, garlic, and cardamom, flame-grilled to absolute tenderness. Served with a side of mild mint-cilantro dipping sauce.',
    price: 490,
    category: 'kebabs',
    origin: 'Flame-Grilled',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&q=80&w=600',
    rating: 4.9,
    reviewsCount: 156,
    ingredients: ['Sirloin Beef', 'Berbere Marination', 'Cardamom', 'Garlic', 'Mint Sauce', 'Onions'],
    calories: 510,
    prepTime: '15 mins',
    isVegetarian: false,
    isPopular: true
  },
  {
    id: '17',
    name: 'Spiced Lamb Rib Chops',
    description: 'Premium cut lamb chops seared over hot open firewood, basted with spiced clarified butter and seasoned with fresh rosemary and garlic.',
    price: 680,
    category: 'kebabs',
    origin: 'Flame-Grilled',
    image: 'https://images.unsplash.com/photo-1600891964599-f61ba0e24092?auto=format&fit=crop&q=80&w=600',
    rating: 5.0,
    reviewsCount: 198,
    ingredients: ['Lamb Chops', 'Niter Kibbeh', 'Rosemary', 'Garlic', 'Sea Salt', 'Black Pepper'],
    calories: 590,
    prepTime: '18 mins',
    isVegetarian: false,
    isPopular: true
  },
  {
    id: '18',
    name: 'Tegabino Shiro Wat',
    description: 'An elevated, extra thick version of our famous ground chickpea stew, prepared with caramelized onions, garlic, and extra portions of spiced clarified butter, served sizzling in a clay bowl.',
    price: 410,
    category: 'mains',
    origin: 'Ethiopian',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=600',
    rating: 4.9,
    reviewsCount: 204,
    ingredients: ['Ground Chickpea Flour', 'Niter Kibbeh', 'Garlic', 'Onions', 'Berbere', 'Spiced Herbs'],
    calories: 460,
    prepTime: '15 mins',
    isVegetarian: false,
    isPopular: true
  },
  {
    id: '19',
    name: 'Zilzil Sizzling Beef Strips',
    description: 'Long tender strips of premium beef sautéed with sliced sweet onions, garlic cloves, fresh jalapeño rings, and rosemary, served in a steaming hot skillet.',
    price: 580,
    category: 'kebabs',
    origin: 'Ethiopian',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=600',
    rating: 4.8,
    reviewsCount: 175,
    ingredients: ['Beef Strips', 'Sweet Onions', 'Garlic', 'Jalapeño Rings', 'Rosemary', 'Butter'],
    calories: 580,
    prepTime: '14 mins',
    isVegetarian: false,
    isPopular: false
  },
  {
    id: '20',
    name: 'Avocado & Beetroot Salad',
    description: 'A vibrant modern fusion salad of crisp garden greens, sweet roasted beetroot chunks, and creamy sliced avocados, tossed in a light ginger-lemon dressing.',
    price: 280,
    category: 'salads',
    origin: 'Modern Fusion',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&q=80&w=600',
    rating: 4.7,
    reviewsCount: 94,
    ingredients: ['Avocados', 'Roasted Beetroot', 'Mixed Greens', 'Ginger', 'Lemon Juice', 'Olive Oil'],
    calories: 210,
    prepTime: '8 mins',
    isVegetarian: true,
    isPopular: false
  },
  {
    id: '21',
    name: 'Spiced Cardamom Fudge Cake',
    description: 'A moist, decadent chocolate fudge cake infused with freshly ground green cardamom, cinnamon, and espresso. Served warm with a scoop of vanilla bean ice cream.',
    price: 280,
    category: 'desserts',
    origin: 'Ethiopian Style',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&q=80&w=600',
    rating: 4.9,
    reviewsCount: 142,
    ingredients: ['Cocoa Powder', 'Cardamom', 'Espresso', 'Flour', 'Butter', 'Vanilla Ice Cream', 'Fudge'],
    calories: 420,
    prepTime: '12 mins',
    isVegetarian: true,
    isPopular: true
  }
];

